//! Core SQL AST, typed expressions, query builders, and PostgreSQL rendering for `fuwa`.
//!
//! This crate does not execute queries. It owns the type-aware DSL surface and renders
//! deterministic PostgreSQL SQL with separately owned bind parameters.

mod bind;
mod error;
mod expr;
mod ident;
mod query;
mod raw;
mod render;
mod selectable;
mod table;

pub use bind::{bind, BindParam, BindValue, IntoBindValue};
pub use error::{Error, Result};
pub use expr::{
    abs, array_agg, avg, bool_and, bool_or, case_when, cast, ceil, coalesce, concat, count,
    count_star, current_row, date_trunc, dense_rank, exists, extract, first_value, floor,
    following, greatest, jsonb_array_length, lag, last_value, lead, least, length, lower, max, min,
    not, not_exists, now, ntile, nullable, nullif, partition_by, preceding, rank, round,
    row_number, string_agg, sum, trim, unbounded_following, unbounded_preceding, upper,
    AliasedExpr, ArithmeticOp, ArrayAggInput, ArrayQuantifier, AvgOutput, BinaryOp, CaseWhen,
    CaseWhenStart, CoalesceArgs, CoalesceNullability, CoalesceNullabilityList, Condition,
    DateTruncOutput, Expr, ExprNode, FieldRef, InOperand, InOperandNode, IntoCondition,
    IntoExistsQuery, IntoExpr, NullableIfEither, OrderDirection, OrderExpr, RoundingOutput,
    SqlArrayElement, SqlJsonb, SqlNumeric, SqlTemporal, SqlType, SumOutput, UnaryOp, WindowFrame,
    WindowFrameBound, WindowFrameUnit, WindowFunction, WindowSpec,
};
pub use ident::quote_ident;
pub use query::{
    delete_from, insert_into, select, update, with, Assignment, Assignments, ConflictTarget,
    Context, DeleteQuery, Excluded, ExprList, ForLock, InsertConflictBuilder, InsertQuery, Join,
    JoinKind, JoinTarget, LockStrength, LockTargetList, LockWait, OrderByList, SelectQuery, SetOp,
    SetOpItem, UpdateQuery, WithBuilder,
};
pub use raw::{raw, RawQuery};
pub use render::{Query, RenderQuery, RenderedQuery};
pub use selectable::{
    selection_as, NotSingleColumn, NullabilityOutput, SelectItem, Selectable, SelectionAs,
};
pub use table::{
    AliasedSubquery, Field, FieldSources, NotNull, Nullable, Table, TableSource, TableSourceRef,
};

/// Common imports for code generated by `fuwa-codegen` and hand-written queries.
pub mod prelude {
    pub use crate::{
        abs, array_agg, avg, bind, bool_and, bool_or, case_when, cast, ceil, coalesce, concat,
        count, count_star, current_row, date_trunc, delete_from, dense_rank, exists, extract,
        first_value, floor, following, greatest, insert_into, jsonb_array_length, lag, last_value,
        lead, least, length, lower, max, min, not, not_exists, now, ntile, nullable, nullif,
        partition_by, preceding, rank, raw, round, row_number, select, selection_as, string_agg,
        sum, trim, unbounded_following, unbounded_preceding, update, upper, with, AliasedExpr,
        AliasedSubquery, ArrayAggInput, Assignment, Assignments, AvgOutput, CaseWhen,
        CaseWhenStart, Condition, ConflictTarget, Context, DateTruncOutput, DeleteQuery, Error,
        Excluded, Expr, ExprList, Field, FieldSources, InOperand, InsertConflictBuilder,
        InsertQuery, IntoCondition, IntoExpr, NotNull, NotSingleColumn, Nullable, OrderByList,
        OrderDirection, OrderExpr, Query, RawQuery, RenderQuery, RenderedQuery, Result,
        RoundingOutput, SelectQuery, Selectable, SqlArrayElement, SqlJsonb, SqlTemporal, SqlType,
        SumOutput, Table, TableSource, UpdateQuery, WindowFrameBound, WindowFunction, WindowSpec,
        WithBuilder,
    };
}
