//! Core SQL AST, typed expressions, query builders, and PostgreSQL rendering for `fuwa`.
//!
//! This crate does not execute queries. It owns the type-aware DSL surface and renders
//! deterministic PostgreSQL SQL with separately owned bind parameters.

mod bind;
mod error;
mod expr;
mod ident;
mod query;
mod raw;
mod render;
mod selectable;
mod table;

pub use bind::{bind, BindParam, BindValue, IntoBindValue};
pub use error::{Error, Result};
pub use expr::{
    count, count_star, jsonb_array_length, not, nullable, sum, BinaryOp, Condition, Expr, ExprNode,
    FieldRef, IntoExpr, OrderDirection, OrderExpr, SumOutput, UnaryOp,
};
pub use ident::quote_ident;
pub use query::{
    Assignment, Assignments, Context, DeleteQuery, InsertQuery, Join, JoinKind, JoinTarget,
    OrderByList, SelectQuery, UpdateQuery,
};
pub use raw::{raw, RawQuery};
pub use render::{RenderQuery, RenderedQuery};
pub use selectable::{selection_as, NullabilityOutput, SelectItem, Selectable, SelectionAs};
pub use table::{Field, NotNull, Nullable, Table};

/// Common imports for code generated by `fuwa-codegen` and hand-written queries.
pub mod prelude {
    pub use crate::{
        bind, count, count_star, jsonb_array_length, not, nullable, raw, selection_as, sum,
        Assignment, Assignments, Condition, Context, DeleteQuery, Error, Expr, Field, InsertQuery,
        IntoExpr, NotNull, Nullable, OrderByList, OrderDirection, OrderExpr, RawQuery, RenderQuery,
        RenderedQuery, Result, SelectQuery, Selectable, SumOutput, Table, UpdateQuery,
    };
}
