//! Core SQL AST, typed expressions, query builders, and PostgreSQL rendering for `fuwa`.
//!
//! This crate does not execute queries. It owns the type-aware DSL surface and renders
//! deterministic PostgreSQL SQL with separately owned bind parameters.

mod bind;
mod error;
mod expr;
mod ident;
mod query;
mod raw;
mod render;
mod selectable;
mod table;

pub use bind::{bind, BindParam, BindValue, IntoBindValue};
pub use error::{Error, Result};
pub use expr::{
    array_agg, avg, bool_and, bool_or, case_when, coalesce, concat, count, count_star,
    jsonb_array_length, max, min, not, nullable, nullif, string_agg, sum, ArithmeticOp,
    ArrayAggInput, AvgOutput, BinaryOp, CaseWhen, CaseWhenStart, CoalesceArgs, CoalesceNullability,
    CoalesceNullabilityList, Condition, Expr, ExprNode, FieldRef, IntoExpr, NullableIfEither,
    OrderDirection, OrderExpr, SqlNumeric, SumOutput, UnaryOp,
};
pub use ident::quote_ident;
pub use query::{
    Assignment, Assignments, ConflictTarget, Context, DeleteQuery, Excluded, ExprList,
    InsertConflictBuilder, InsertQuery, Join, JoinKind, JoinTarget, OrderByList, SelectQuery,
    UpdateQuery,
};
pub use raw::{raw, RawQuery};
pub use render::{RenderQuery, RenderedQuery};
pub use selectable::{selection_as, NullabilityOutput, SelectItem, Selectable, SelectionAs};
pub use table::{Field, NotNull, Nullable, Table};

/// Common imports for code generated by `fuwa-codegen` and hand-written queries.
pub mod prelude {
    pub use crate::{
        array_agg, avg, bind, bool_and, bool_or, case_when, coalesce, concat, count, count_star,
        jsonb_array_length, max, min, not, nullable, nullif, raw, selection_as, string_agg, sum,
        ArrayAggInput, Assignment, Assignments, AvgOutput, CaseWhen, CaseWhenStart, Condition,
        ConflictTarget, Context, DeleteQuery, Error, Excluded, Expr, ExprList, Field,
        InsertConflictBuilder, InsertQuery, IntoExpr, NotNull, Nullable, OrderByList,
        OrderDirection, OrderExpr, RawQuery, RenderQuery, RenderedQuery, Result, SelectQuery,
        Selectable, SumOutput, Table, UpdateQuery,
    };
}
